# Generated by Django 3.2.5 on 2023-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='long_description',
            field=models.TextField(null=True),
        ),
    ]
