# Generated by Django 3.2.5 on 2023-03-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_location_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='host_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
