# Generated by Django 3.2.5 on 2023-03-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20230319_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
