# Generated by Django 3.2.5 on 2023-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotel_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.IntegerField(default=1),
        ),
    ]
