# Generated by Django 3.2.5 on 2023-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20230319_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
