# Generated by Django 3.2.5 on 2023-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_booking_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
